# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_project.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1252, 627)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.abaddon_button = QtWidgets.QPushButton(self.centralwidget)
        self.abaddon_button.setGeometry(QtCore.QRect(0, 10, 150, 84))
        self.abaddon_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ProjecX/Images/Abaddon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.abaddon_button.setIcon(icon)
        self.abaddon_button.setIconSize(QtCore.QSize(150, 84))
        self.abaddon_button.setObjectName("abaddon_button")
        self.alchemist_button = QtWidgets.QPushButton(self.centralwidget)
        self.alchemist_button.setGeometry(QtCore.QRect(160, 10, 150, 84))
        self.alchemist_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ProjecX/Images/Alchemist.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.alchemist_button.setIcon(icon1)
        self.alchemist_button.setIconSize(QtCore.QSize(150, 84))
        self.alchemist_button.setObjectName("alchemist_button")
        self.axe_button = QtWidgets.QPushButton(self.centralwidget)
        self.axe_button.setGeometry(QtCore.QRect(320, 10, 150, 84))
        self.axe_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ProjecX/Images/Axe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.axe_button.setIcon(icon2)
        self.axe_button.setIconSize(QtCore.QSize(150, 84))
        self.axe_button.setObjectName("axe_button")
        self.beastmaster_button = QtWidgets.QPushButton(self.centralwidget)
        self.beastmaster_button.setGeometry(QtCore.QRect(480, 10, 150, 84))
        self.beastmaster_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ProjecX/Images/Beastmaster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.beastmaster_button.setIcon(icon3)
        self.beastmaster_button.setIconSize(QtCore.QSize(150, 84))
        self.beastmaster_button.setObjectName("beastmaster_button")
        self.cw_button = QtWidgets.QPushButton(self.centralwidget)
        self.cw_button.setGeometry(QtCore.QRect(960, 10, 150, 84))
        self.cw_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ProjecX/Images/Centaur Warrunner.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cw_button.setIcon(icon4)
        self.cw_button.setIconSize(QtCore.QSize(150, 84))
        self.cw_button.setObjectName("cw_button")
        self.bristleback_button = QtWidgets.QPushButton(self.centralwidget)
        self.bristleback_button.setGeometry(QtCore.QRect(800, 10, 150, 84))
        self.bristleback_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ProjecX/Images/Bristleback.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bristleback_button.setIcon(icon5)
        self.bristleback_button.setIconSize(QtCore.QSize(150, 84))
        self.bristleback_button.setObjectName("bristleback_button")
        self.brewmaster_button = QtWidgets.QPushButton(self.centralwidget)
        self.brewmaster_button.setGeometry(QtCore.QRect(640, 10, 150, 84))
        self.brewmaster_button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ProjecX/Images/Brewmaster.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.brewmaster_button.setIcon(icon6)
        self.brewmaster_button.setIconSize(QtCore.QSize(150, 84))
        self.brewmaster_button.setObjectName("brewmaster_button")
        self.ck_button = QtWidgets.QPushButton(self.centralwidget)
        self.ck_button.setGeometry(QtCore.QRect(0, 100, 150, 84))
        self.ck_button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ProjecX/Images/Chaos Knight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ck_button.setIcon(icon7)
        self.ck_button.setIconSize(QtCore.QSize(150, 84))
        self.ck_button.setObjectName("ck_button")
        self.dk_button = QtWidgets.QPushButton(self.centralwidget)
        self.dk_button.setGeometry(QtCore.QRect(480, 100, 150, 84))
        self.dk_button.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ProjecX/Images/Dragon Knight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dk_button.setIcon(icon8)
        self.dk_button.setIconSize(QtCore.QSize(150, 84))
        self.dk_button.setObjectName("dk_button")
        self.doom_button = QtWidgets.QPushButton(self.centralwidget)
        self.doom_button.setGeometry(QtCore.QRect(320, 100, 150, 84))
        self.doom_button.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("ProjecX/Images/Doom.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.doom_button.setIcon(icon9)
        self.doom_button.setIconSize(QtCore.QSize(150, 84))
        self.doom_button.setObjectName("doom_button")
        self.earth_button = QtWidgets.QPushButton(self.centralwidget)
        self.earth_button.setGeometry(QtCore.QRect(640, 100, 150, 84))
        self.earth_button.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("ProjecX/Images/Earth Spirit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.earth_button.setIcon(icon10)
        self.earth_button.setIconSize(QtCore.QSize(150, 84))
        self.earth_button.setObjectName("earth_button")
        self.clockwerk_button = QtWidgets.QPushButton(self.centralwidget)
        self.clockwerk_button.setGeometry(QtCore.QRect(160, 100, 150, 84))
        self.clockwerk_button.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("ProjecX/Images/Clockwerk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clockwerk_button.setIcon(icon11)
        self.clockwerk_button.setIconSize(QtCore.QSize(150, 84))
        self.clockwerk_button.setObjectName("clockwerk_button")
        self.et_button = QtWidgets.QPushButton(self.centralwidget)
        self.et_button.setGeometry(QtCore.QRect(960, 100, 150, 84))
        self.et_button.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("ProjecX/Images/Elder Titan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.et_button.setIcon(icon12)
        self.et_button.setIconSize(QtCore.QSize(150, 84))
        self.et_button.setObjectName("et_button")
        self.es_button = QtWidgets.QPushButton(self.centralwidget)
        self.es_button.setGeometry(QtCore.QRect(800, 100, 150, 84))
        self.es_button.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("ProjecX/Images/Earthshaker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.es_button.setIcon(icon13)
        self.es_button.setIconSize(QtCore.QSize(150, 84))
        self.es_button.setObjectName("es_button")
        self.lifestealer_button = QtWidgets.QPushButton(self.centralwidget)
        self.lifestealer_button.setGeometry(QtCore.QRect(640, 190, 150, 84))
        self.lifestealer_button.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap("ProjecX/Images/Lifestealer.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lifestealer_button.setIcon(icon14)
        self.lifestealer_button.setIconSize(QtCore.QSize(150, 84))
        self.lifestealer_button.setObjectName("lifestealer_button")
        self.kunkka_button = QtWidgets.QPushButton(self.centralwidget)
        self.kunkka_button.setGeometry(QtCore.QRect(320, 190, 150, 84))
        self.kunkka_button.setText("")
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap("ProjecX/Images/Kunkka.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.kunkka_button.setIcon(icon15)
        self.kunkka_button.setIconSize(QtCore.QSize(150, 84))
        self.kunkka_button.setObjectName("kunkka_button")
        self.io_button = QtWidgets.QPushButton(self.centralwidget)
        self.io_button.setGeometry(QtCore.QRect(160, 190, 150, 84))
        self.io_button.setText("")
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap("ProjecX/Images/Io.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.io_button.setIcon(icon16)
        self.io_button.setIconSize(QtCore.QSize(150, 84))
        self.io_button.setObjectName("io_button")
        self.lycan_button = QtWidgets.QPushButton(self.centralwidget)
        self.lycan_button.setGeometry(QtCore.QRect(800, 190, 150, 84))
        self.lycan_button.setText("")
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap("ProjecX/Images/Lycan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lycan_button.setIcon(icon17)
        self.lycan_button.setIconSize(QtCore.QSize(150, 84))
        self.lycan_button.setObjectName("lycan_button")
        self.magnus_button = QtWidgets.QPushButton(self.centralwidget)
        self.magnus_button.setGeometry(QtCore.QRect(960, 190, 150, 84))
        self.magnus_button.setText("")
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap("ProjecX/Images/Magnus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.magnus_button.setIcon(icon18)
        self.magnus_button.setIconSize(QtCore.QSize(150, 84))
        self.magnus_button.setObjectName("magnus_button")
        self.huskar_button = QtWidgets.QPushButton(self.centralwidget)
        self.huskar_button.setGeometry(QtCore.QRect(0, 190, 150, 84))
        self.huskar_button.setText("")
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap("ProjecX/Images/Huskar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.huskar_button.setIcon(icon19)
        self.huskar_button.setIconSize(QtCore.QSize(150, 84))
        self.huskar_button.setObjectName("huskar_button")
        self.lc_button = QtWidgets.QPushButton(self.centralwidget)
        self.lc_button.setGeometry(QtCore.QRect(480, 190, 150, 84))
        self.lc_button.setText("")
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap("ProjecX/Images/Legion Commander.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lc_button.setIcon(icon20)
        self.lc_button.setIconSize(QtCore.QSize(150, 84))
        self.lc_button.setObjectName("lc_button")
        self.pudge_button = QtWidgets.QPushButton(self.centralwidget)
        self.pudge_button.setGeometry(QtCore.QRect(640, 280, 150, 84))
        self.pudge_button.setText("")
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap("ProjecX/Images/Pudge.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pudge_button.setIcon(icon21)
        self.pudge_button.setIconSize(QtCore.QSize(150, 84))
        self.pudge_button.setObjectName("pudge_button")
        self.omniknight_button = QtWidgets.QPushButton(self.centralwidget)
        self.omniknight_button.setGeometry(QtCore.QRect(320, 280, 150, 84))
        self.omniknight_button.setText("")
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap("ProjecX/Images/Omniknight.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.omniknight_button.setIcon(icon22)
        self.omniknight_button.setIconSize(QtCore.QSize(150, 84))
        self.omniknight_button.setObjectName("omniknight_button")
        self.ns_button = QtWidgets.QPushButton(self.centralwidget)
        self.ns_button.setGeometry(QtCore.QRect(160, 280, 150, 84))
        self.ns_button.setText("")
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap("ProjecX/Images/Night Stalker.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ns_button.setIcon(icon23)
        self.ns_button.setIconSize(QtCore.QSize(150, 84))
        self.ns_button.setObjectName("ns_button")
        self.sk_button = QtWidgets.QPushButton(self.centralwidget)
        self.sk_button.setGeometry(QtCore.QRect(800, 280, 150, 84))
        self.sk_button.setText("")
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap("ProjecX/Images/Sand King.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sk_button.setIcon(icon24)
        self.sk_button.setIconSize(QtCore.QSize(150, 84))
        self.sk_button.setObjectName("sk_button")
        self.slardar_button = QtWidgets.QPushButton(self.centralwidget)
        self.slardar_button.setGeometry(QtCore.QRect(960, 280, 150, 84))
        self.slardar_button.setText("")
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap("ProjecX/Images/Slardar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.slardar_button.setIcon(icon25)
        self.slardar_button.setIconSize(QtCore.QSize(150, 84))
        self.slardar_button.setObjectName("slardar_button")
        self.mars_button = QtWidgets.QPushButton(self.centralwidget)
        self.mars_button.setGeometry(QtCore.QRect(0, 280, 150, 84))
        self.mars_button.setText("")
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap("ProjecX/Images/Mars.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mars_button.setIcon(icon26)
        self.mars_button.setIconSize(QtCore.QSize(150, 84))
        self.mars_button.setObjectName("mars_button")
        self.phoenix_button = QtWidgets.QPushButton(self.centralwidget)
        self.phoenix_button.setGeometry(QtCore.QRect(480, 280, 150, 84))
        self.phoenix_button.setText("")
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap("ProjecX/Images/Phoenix.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.phoenix_button.setIcon(icon27)
        self.phoenix_button.setIconSize(QtCore.QSize(150, 84))
        self.phoenix_button.setObjectName("phoenix_button")
        self.undying_button = QtWidgets.QPushButton(self.centralwidget)
        self.undying_button.setGeometry(QtCore.QRect(640, 370, 150, 84))
        self.undying_button.setText("")
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap("ProjecX/Images/Undying.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.undying_button.setIcon(icon28)
        self.undying_button.setIconSize(QtCore.QSize(150, 84))
        self.undying_button.setObjectName("undying_button")
        self.underlord_button = QtWidgets.QPushButton(self.centralwidget)
        self.underlord_button.setGeometry(QtCore.QRect(320, 370, 150, 84))
        self.underlord_button.setText("")
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap("ProjecX/Images/Underlord.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.underlord_button.setIcon(icon29)
        self.underlord_button.setIconSize(QtCore.QSize(150, 84))
        self.underlord_button.setObjectName("underlord_button")
        self.tusk_button = QtWidgets.QPushButton(self.centralwidget)
        self.tusk_button.setGeometry(QtCore.QRect(160, 370, 150, 84))
        self.tusk_button.setText("")
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap("ProjecX/Images/Tusk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tusk_button.setIcon(icon30)
        self.tusk_button.setIconSize(QtCore.QSize(150, 84))
        self.tusk_button.setObjectName("tusk_button")
        self.wk_button = QtWidgets.QPushButton(self.centralwidget)
        self.wk_button.setGeometry(QtCore.QRect(800, 370, 150, 84))
        self.wk_button.setText("")
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap("ProjecX/Images/Wraith King.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.wk_button.setIcon(icon31)
        self.wk_button.setIconSize(QtCore.QSize(150, 84))
        self.wk_button.setObjectName("wk_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1252, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
